# Generated by Django 6.0 on 2026-01-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('price', models.IntegerField(verbose_name='ราคา (บาท)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='รูปภาพสินค้า')),
                ('script_file', models.FileField(blank=True, null=True, upload_to='scripts/', verbose_name='ไฟล์สคริปต์ (ถ้ามี)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
